### ISSUE TITLE
Table cells, tree nodes and labels should support text-styling attributes

### ISSUE THREAD

**Issue by ndreynolds** [ndreynolds/ratatouille#2]
The `table_cell`, `tree_node` and `label` elements should support all the text styling attributes supported by `text` elements (`background`, `color`, `attributes`).

* [x] - `table_cell`
* [x] - `tree_node`
* [x] - `label`
* [x] - `panel`

**Comment by iboard** [comment]
I did this for `panel` see https://github.com/ndreynolds/ratatouille/pull/4

**Comment by ndreynolds** [comment]
These are all done on the master branch now, so I'll close this one.

I'm still thinking about how to design the rest of the styling API.  It could make sense to support cascading styles like CSS (e.g., I define `color` on a `panel` and it becomes the default `color` for all child elements).  But that might also just overcomplicate things  :thinking:
